account = "atxug04702.australia-southeast2.gcp"
user = "ACME_ADMIN"
password = "RamVinayak@1810"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
# Streamlit secrets configuration
